apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backup
  namespace: '{{ "NAMESPACE" | env }}'
data:
  sentry-dsn: '{{ "SENTRY_DSN_KEY" | env | teamvaultUrl | base64 }}'
  id_backup: '{{ "BACKUP_SSH_KEY" | env | teamvaultFile | base64 }}'
