apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - backup.benjamin-borbe.de
    resources:
      - targets
    verbs:
      - list
      - watch
      - get
