// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1 "github.com/bborbe/backup/k8s/apis/backup.benjamin-borbe.de/v1"
	backupbenjaminborbedev1 "github.com/bborbe/backup/k8s/client/applyconfiguration/backup.benjamin-borbe.de/v1"
)

// FakeTargets implements TargetInterface
type FakeTargets struct {
	Fake *FakeMonitoringV1
	ns   string
}

var targetsResource = v1.SchemeGroupVersion.WithResource("targets")

var targetsKind = v1.SchemeGroupVersion.WithKind("Target")

// Get takes name of the target, and returns the corresponding target object, and an error if there is any.
func (c *FakeTargets) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Target, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(targetsResource, c.ns, name), &v1.Target{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Target), err
}

// List takes label and field selectors, and returns the list of Targets that match those selectors.
func (c *FakeTargets) List(ctx context.Context, opts metav1.ListOptions) (result *v1.TargetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(targetsResource, targetsKind, c.ns, opts), &v1.TargetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.TargetList{ListMeta: obj.(*v1.TargetList).ListMeta}
	for _, item := range obj.(*v1.TargetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested targets.
func (c *FakeTargets) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(targetsResource, c.ns, opts))

}

// Create takes the representation of a target and creates it.  Returns the server's representation of the target, and an error, if there is any.
func (c *FakeTargets) Create(ctx context.Context, target *v1.Target, opts metav1.CreateOptions) (result *v1.Target, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(targetsResource, c.ns, target), &v1.Target{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Target), err
}

// Update takes the representation of a target and updates it. Returns the server's representation of the target, and an error, if there is any.
func (c *FakeTargets) Update(ctx context.Context, target *v1.Target, opts metav1.UpdateOptions) (result *v1.Target, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(targetsResource, c.ns, target), &v1.Target{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Target), err
}

// Delete takes name of the target and deletes it. Returns an error if one occurs.
func (c *FakeTargets) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(targetsResource, c.ns, name, opts), &v1.Target{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTargets) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(targetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.TargetList{})
	return err
}

// Patch applies the patch and returns the patched target.
func (c *FakeTargets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Target, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(targetsResource, c.ns, name, pt, data, subresources...), &v1.Target{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Target), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied target.
func (c *FakeTargets) Apply(ctx context.Context, target *backupbenjaminborbedev1.TargetApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Target, err error) {
	if target == nil {
		return nil, fmt.Errorf("target provided to Apply must not be nil")
	}
	data, err := json.Marshal(target)
	if err != nil {
		return nil, err
	}
	name := target.Name
	if name == nil {
		return nil, fmt.Errorf("target.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(targetsResource, c.ns, *name, types.ApplyPatchType, data), &v1.Target{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Target), err
}
